# Generated by Django 3.1.14 on 2022-01-22 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracelets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracelet',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bracelet',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='braceletimage',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
