# Generated by Django 3.1.14 on 2022-01-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracelets', '0002_auto_20220121_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='braceletimage',
            name='image',
            field=models.ImageField(null=True, upload_to='bracelets'),
        ),
    ]
