# Generated by Django 3.1.14 on 2022-02-03 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bracelets', '0003_auto_20220125_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earing',
            fields=[
                ('bracelet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bracelets.bracelet')),
            ],
            bases=('bracelets.bracelet',),
        ),
        migrations.AddField(
            model_name='bracelet',
            name='available',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bracelet',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
