# Generated by Django 3.1.14 on 2022-02-03 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bracelets', '0004_auto_20220202_2139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BraceletImage',
        ),
        migrations.DeleteModel(
            name='Earing',
        ),
    ]
