# Generated by Django 3.1.14 on 2022-02-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracelets', '0006_auto_20220202_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('br', 'bracelet'), ('er', 'earing'), ('ot', 'other')], default='ot', max_length=2),
        ),
    ]
